export default {
    init: "/init",
    login: "/",
    home: "/home",
    historial: "/historial",
    map: "/map",
    account: "/account",
    camera: "/camera",
    security: "/security",
    qr: "/qr",
    chooseEnterprise: "/chooseEnterprise",
    personalData: "/personalData",
    configuration: "/configuration",
    operar: "/operar",
    incidencias: "/incidencias",
    crearIncidencia: "/crear-incidencia",
}